mode: "dev"
port: 8083

base:
  auth: "password"
  publicKey: "/root/.ssh/id_rsa"
  user: "root"
  passwd: "123456"
  port: 22
  des_path: "/tmp/xxxaa"           #目标路径
  src_path: "D:\\workspaces\\go\\config-check\\rpm"    #本地路径

log:
  level: "debug"
  filename: "./log/app.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

localserver:
#已有机器检测
  servers: [
      "192.168.10.86",
      "192.168.10.87",
      "192.168.10.88"
  ]

riceiplist:
#远程地址信息
  rice_list: [
      "111.111.46.200:443",
      "111.111.46.200:18888",
      "222.111.46.200:48888"
  ]


ncportlist:
#互通检测信息
  nc_port_list: [
      "644",
      "707",
      "237",
  ]
